### PR TITLE
Public `poll_service_state`

### PR DESCRIPTION
**Pull request by Hackerman342**

### CODE REVIEW

**Review by christopherbradski — APPROVED** [review]

**Review by edgarriba — COMMENTED** [review]
Be aware that sleep in poll is 0.5 , that might affect performance of apps. /cc @ethanrublee

**Comment by Hackerman342** [comment]
> Be aware that sleep in poll is 0.5 , that might affect performance of apps. /cc @ethanrublee
@edgarriba The point is to keep the check asynchronous to improve performance (not `await get_state()` each loop). Since we're relying on this, should we decrease the sleep for `poll_service_state`?

**Comment by edgarriba** [comment]
yes, otherwise we'll slow down the sensors stream tasks

**Comment by Hackerman342** [comment]
How so? It's asynchronous

**Pull request merged**
